### PR TITLE
Switched to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
This library will improve performance and greatly reduce memory allocations through object pooling of SemaphoreSlim objects.

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@vladimir-litvinchik :)

**Comment by MarkCiliaVincenti** [comment]
@vladimir-litvinchik ?

**Comment by MarkCiliaVincenti** [comment]
@vladimir-litvinchik ?

**Comment by vladimir-litvinchik** [comment]
@MarkCiliaVincenti 

At the moment I'm not going to merge these changes due to security reasons.  I'm sorry for the inconvenience.

**Comment by MarkCiliaVincenti** [comment]
> @MarkCiliaVincenti
> 
> At the moment I'm not going to merge these changes due to security reasons. I'm sorry for the inconvenience.

Hi Vladimir,

Just to be clear, by security reasons you mean due to dragging in a dependency not because you found some bug, right? Would you be willing to consider it in the future if the library sees a big increase in dependents?

**Comment by vladimir-litvinchik** [comment]
@MarkCiliaVincenti 

`GroupDocs.Viewer.UI` published as our public NuGet package. We're signing this and related packages. Unfortunately, I don't have time to keep track of changes in your package. This is why I can't include it as a dependency.

**Pull request closed without merging**
